server:
  address: 127.0.0.1
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: oauth
  messages:
    basename: i18n/Messages,i18n/Pages
  #

  profiles:
    active: prod

  thymeleaf:
#    prefix:
    cache: false
    enabled: true  #开启thymeleaf视图解析
    prefix: classpath:/templates/
    suffix: .html

  resources:
    static-locations: classpath:/static/
    #  mvc:
#    static-path-pattern: /static/**

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  aop:
    proxy-target-class: true

  devtools:
    restart:
      enabled: true

mybatis:
  type-aliases-package: com.seeini.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    cache-enabled: true
    aggressive-lazy-loading: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true







